/*+++ USER TABLES+++ */
CREATE TABLE `usuarios`.`users` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `FULLNAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PHONE` VARCHAR(45) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `CREATED AT` VARCHAR(45) NOT NULL,
  `UPDATED_AT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC) VISIBLE);

ALTER TABLE `usuarios`.`users` 
    ADD COLUMN `ROLE` VARCHAR(45) NOT NULL AFTER `PASSWORD

ALTER TABLE `delilahresto`.`users` 
CHANGE COLUMN `CREATED AT` `CREATED AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN `UPDATED_AT` `UPDATED_AT` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP ;

ALTER TABLE `delilahresto`.`users` 
CHANGE COLUMN `PASSWORD` `PASSWORD` VARCHAR(256) NOT NULL ;

ALTER TABLE `delilahresto`.`users` 
CHANGE COLUMN `CREATED AT` `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ;




CREATE TABLE `delilahresto`.`items` (
  `ITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `SHORT_DESC` VARCHAR(100) NOT NULL,
  `PRICE` FLOAT NOT NULL,
  `STATUS` VARCHAR(100) NOT NULL,
  `CREATED_BY` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) NULL,
  `UPDATED_AT` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ITEM_ID`));


ALTER TABLE `delilahresto`.`items` 
CHANGE COLUMN `CREATED_AT` `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `delilahresto`.`items` 
ADD COLUMN `PHOTO_URL` VARCHAR(256) NOT NULL AFTER `SHORT_DESC`;

ALTER TABLE `delilahresto`.`items` 
CHANGE COLUMN `STATUS` `STATUS` VARCHAR(100) NULL DEFAULT 'ACTIVE' ;




CREATE TABLE `delilahresto`.`favorites` (
  `USER_ID` VARCHAR(45) NOT NULL,
  `ITEM_ID` INT NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE `delilahresto`.`favorites` 
CHANGE COLUMN `USER_ID` `USERNAME` VARCHAR(45) NOT NULL ;

ALTER TABLE `delilahresto`.`favorites` 
ADD INDEX `USER_idx` (`USERNAME` ASC) VISIBLE;
;
ALTER TABLE `delilahresto`.`favorites` 
ADD CONSTRAINT `USER`
  FOREIGN KEY (`USERNAME`)
  REFERENCES `delilahresto`.`users` (`USERNAME`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `delilahresto`.`favorites` 
ADD INDEX `ITEM_idx` (`ITEM_ID` ASC) VISIBLE;
;
ALTER TABLE `delilahresto`.`favorites` 
ADD CONSTRAINT `ITEM`
  FOREIGN KEY (`ITEM_ID`)
  REFERENCES `delilahresto`.`items` (`ITEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;



CREATE TABLE `delilahresto`.`orders` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(256) NOT NULL,
  `PAYMENT_METHOD` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `CREATED_BY` VARCHAR(45) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_CHANGE_STATE_BY` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_CHANGE_STATE_AT` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_ID`));

ALTER TABLE `delilahresto`.`orders` 
ADD INDEX `USER_ORDERS_idx` (`CREATED_BY` ASC) VISIBLE;
;
ALTER TABLE `delilahresto`.`orders` 
ADD CONSTRAINT `USER_ORDERS`
  FOREIGN KEY (`CREATED_BY`)
  REFERENCES `delilahresto`.`users` (`USERNAME`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `delilahresto`.`orders` 
ADD COLUMN `TOTAL` VARCHAR(45) NULL AFTER `PAYMENT_METHOD`;

ALTER TABLE `delilahresto`.`orders` 
CHANGE COLUMN `TOTAL` `TOTAL` DECIMAL NULL DEFAULT NULL ;

ALTER TABLE `delilahresto`.`orders` 
CHANGE COLUMN `LAST_CHANGE_STATE_BY` `LAST_STATE_CHANGE_BY` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `LAST_CHANGE_STATE_AT` `LAST_STATE_CHANGE_AT` TIMESTAMP NULL DEFAULT NULL ;



CREATE TABLE `delilahresto`.`order_items` (
  `ORDER_ID` INT NOT NULL,
  `ITEM_ID` INT NOT NULL,
  `QUANTITY` INT NOT NULL);

ALTER TABLE `delilahresto`.`order_items` 
ADD CONSTRAINT `ORDER_ORDER_ITEMS`
  FOREIGN KEY (`ORDER_ID`)
  REFERENCES `delilahresto`.`orders` (`ORDER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `ITEM_ORDER_ITEMS`
  FOREIGN KEY (`ITEM_ID`)
  REFERENCES `delilahresto`.`items` (`ITEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;



