INSERT INTO delilahresto.users  (USERNAME, FULLNAME, EMAIL, PHONE, ADDRESS, PASSWORD, ROLE) VALUES ('RDJ472007', 'Richard Villamizar', 'rdj47@hotmail.com', '+541167945117', 'san luis', 'clave', 'customer');
INSERT INTO delilahresto.orders  (DESCRIPTION, PAYMENT_METHOD, STATE, CREATED_BY) VALUES ('description', 'Cash', 'NEW', 'RDJ472007');

SELECT a.ORDER_ID, a.DESCRIPTION, a.PAYMENT_METHOD, a.TOTAL, a.STATE, b.ADDRESS, a.CREATED_BY, a.CREATED_AT, a.UPDATED_BY, a.UPDATED_AT FROM orders AS A WHERE ORDER_ID=? INNER JOIN users AS b ON orders.CREATED_BY=users.USERNAME
SELECT a.ORDER_ID, a.ITEM_ID, b.PRICE, a.QUANTITY FROM order_items AS a INNER JOIN items AS b ON a.ITEM_ID=b.ITEM_ID WHERE ORDER_ID=8